version: "3"

services:
  backend:
    build:
      context: ./backend
    container_name: goshopback
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
    container_name: goshopfront
    ports:
      - "5173:5173"
    restart: always
    depends_on:
      - backend
    env_file:
      - .env

  postgres:
    image: postgres:13
    container_name: pqdb
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
