// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package data

import (
	"database/sql"
	"encoding/json"

	"github.com/sqlc-dev/pqtype"
)

type Order struct {
	ID              int64                 `json:"id"`
	UserID          int64                 `json:"user_id"`
	ShippingAddress json.RawMessage       `json:"shipping_address"`
	PaymentMethod   string                `json:"payment_method"`
	PaymentResult   pqtype.NullRawMessage `json:"payment_result"`
	ItemsPrice      string                `json:"items_price"`
	TaxPrice        string                `json:"tax_price"`
	ShippingPrice   string                `json:"shipping_price"`
	TotalPrice      string                `json:"total_price"`
	IsPaid          bool                  `json:"is_paid"`
	PaidAt          sql.NullTime          `json:"paid_at"`
	IsDelivered     bool                  `json:"is_delivered"`
	DeliveredAt     sql.NullTime          `json:"delivered_at"`
	CreatedAt       sql.NullTime          `json:"created_at"`
	UpdatedAt       sql.NullTime          `json:"updated_at"`
}

type OrderItem struct {
	ID        int64        `json:"id"`
	OrderID   int64        `json:"order_id"`
	Name      string       `json:"name"`
	Quantity  int32        `json:"quantity"`
	Image     string       `json:"image"`
	Price     string       `json:"price"`
	ProductID int64        `json:"product_id"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Product struct {
	ID           int64        `json:"id"`
	UserID       int64        `json:"user_id"`
	Name         string       `json:"name"`
	Image        string       `json:"image"`
	Brand        string       `json:"brand"`
	Category     string       `json:"category"`
	Description  string       `json:"description"`
	Rating       string       `json:"rating"`
	NumReviews   int32        `json:"num_reviews"`
	Price        string       `json:"price"`
	CountInStock int32        `json:"count_in_stock"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}

type Review struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	Rating    string       `json:"rating"`
	Comment   string       `json:"comment"`
	UserID    int64        `json:"user_id"`
	ProductID int64        `json:"product_id"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type User struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	Email     string       `json:"email"`
	Password  string       `json:"password"`
	IsAdmin   sql.NullBool `json:"is_admin"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}
